networks:
  blog:
    name: blog

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - blog
    depends_on:
      - php
      - mysql

  php:
    build: docker/php
    volumes:
      - ./www:/var/www/public_html
    networks:
      - blog
    depends_on:
      - mysql

  mysql:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db
    networks:
      - blog

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=root
    networks:
      - blog
    depends_on:
      - mysql

volumes:
  mysql-data: